import 'medicine.dart';
import 'store.dart';

class SampleData {
  static const stores = <Store>[
    Store(
      id: 1,
      name: 'Downtown Branch',
      chain: 'Mercury Drug',
      address: 'Daang Maharlika Highway, Brgy Gredu',
      phone: '(555) 010-1001',
      distanceKm: 0.7,
      isOpen: true,
    ),
    Store(
      id: 2,
      name: 'Westside Branch',
      chain: 'Mercury Drug',
      address: '45 Elm Ave, Westside',
      phone: '(555) 010-1002',
      distanceKm: 2.2,
      isOpen: false,
    ),
    Store(
      id: 3,
      name: 'City Center Branch',
      chain: 'Rose Pharmacy',
      address: 'Panabo Highway, Maharlika Street',
      phone: '(555) 010-2001',
      distanceKm: 1.5,
      isOpen: true,
    ),
    Store(
      id: 4,
      name: 'Gaisano Branch',
      chain: 'Rose Pharmacy',
      address: 'Gaisano Grand Mall, Quezon Street',
      phone: '(555) 010-2002',
      distanceKm: 3.0,
      isOpen: true,
    ),
    Store(
      id: 5,
      name: 'Downtown Branch',
      chain: 'Generika Drugstore',
      address: 'Quezon Street, Panabo Warf',
      phone: '(555) 010-3001',
      distanceKm: 2.8,
      isOpen: true,
    ),
    Store(
      id: 6,
      name: 'Uptown Branch',
      chain: 'Generika Drugstore',
      address: '201 Pine Ave, Uptown',
      phone: '(555) 010-3002',
      distanceKm: 4.6,
      isOpen: false,
    ),
    Store(
      id: 7,
      name: 'Central Branch',
      chain: 'The Generics Pharmacy',
      address: 'Qurino Street, NightMarket',
      phone: '(555) 010-4001',
      distanceKm: 1.9,
      isOpen: true,
    ),
    Store(
      id: 8,
      name: 'Highway Branch',
      chain: 'The Generics Pharmacy',
      address: 'Panabo Warf Road, Bpi Direct',
      phone: '(555) 010-4002',
      distanceKm: 5.2,
      isOpen: true,
    ),
  ];

  static const medicines = <Medicine>[
    Medicine(
      id: 1,
      name: 'Paracetamol',
      dosage: '500mg Tablet',
      price: 1.50,
      stock: 120,
      storeId: 1,
    ),
    Medicine(
      id: 2,
      name: 'Ibuprofen',
      dosage: '200mg Tablet',
      price: 2.00,
      stock: 0,
      storeId: 1,
    ),
    Medicine(
      id: 3,
      name: 'Amoxicillin',
      dosage: '500mg Capsule',
      price: 8.99,
      stock: 25,
      storeId: 2,
    ),
    Medicine(
      id: 4,
      name: 'Aspirin',
      dosage: '325mg Tablet',
      price: 1.75,
      stock: 85,
      storeId: 1,
    ),
    Medicine(
      id: 5,
      name: 'Diphenhydramine',
      dosage: '25mg Tablet',
      price: 2.50,
      stock: 45,
      storeId: 2,
    ),
    Medicine(
      id: 6,
      name: 'Cetirizine',
      dosage: '10mg Tablet',
      price: 1.20,
      stock: 60,
      storeId: 3,
    ),
    Medicine(
      id: 7,
      name: 'Loperamide',
      dosage: '2mg Capsule',
      price: 1.75,
      stock: 0,
      storeId: 4,
    ),
    Medicine(
      id: 8,
      name: 'Loratadine',
      dosage: '10mg Tablet',
      price: 1.80,
      stock: 90,
      storeId: 3,
    ),
    Medicine(
      id: 9,
      name: 'Ranitidine',
      dosage: '150mg Tablet',
      price: 2.99,
      stock: 35,
      storeId: 4,
    ),
    Medicine(
      id: 10,
      name: 'Metronidazole',
      dosage: '250mg Tablet',
      price: 3.25,
      stock: 55,
      storeId: 3,
    ),
    Medicine(
      id: 11,
      name: 'Omeprazole',
      dosage: '20mg Capsule',
      price: 5.99,
      stock: 50,
      storeId: 5,
    ),
    Medicine(
      id: 12,
      name: 'Salbutamol',
      dosage: '2mg/5mL Syrup',
      price: 3.50,
      stock: 10,
      storeId: 6,
    ),
    Medicine(
      id: 13,
      name: 'Fluoxetine',
      dosage: '20mg Capsule',
      price: 7.50,
      stock: 40,
      storeId: 5,
    ),
    Medicine(
      id: 14,
      name: 'Atorvastatin',
      dosage: '20mg Tablet',
      price: 6.75,
      stock: 65,
      storeId: 6,
    ),
    Medicine(
      id: 15,
      name: 'Cough Syrup',
      dosage: '10mg/5mL',
      price: 2.25,
      stock: 0,
      storeId: 5,
    ),
    Medicine(
      id: 16,
      name: 'Metformin',
      dosage: '500mg Tablet',
      price: 4.25,
      stock: 70,
      storeId: 7,
    ),
    Medicine(
      id: 17,
      name: 'Losartan',
      dosage: '50mg Tablet',
      price: 6.10,
      stock: 0,
      storeId: 8,
    ),
    Medicine(
      id: 18,
      name: 'Lisinopril',
      dosage: '10mg Tablet',
      price: 5.50,
      stock: 48,
      storeId: 7,
    ),
    Medicine(
      id: 19,
      name: 'Amlodipine',
      dosage: '5mg Tablet',
      price: 4.99,
      stock: 72,
      storeId: 8,
    ),
    Medicine(
      id: 20,
      name: 'Vitamin C',
      dosage: '500mg Tablet',
      price: 1.50,
      stock: 150,
      storeId: 7,
    ),
    Medicine(
      id: 21,
      name: 'Multivitamin',
      dosage: 'Daily Formula',
      price: 3.99,
      stock: 95,
      storeId: 8,
    ),
    Medicine(
      id: 22,
      name: 'Iron Supplement',
      dosage: '65mg Tablet',
      price: 2.75,
      stock: 58,
      storeId: 7,
    ),
  ];
}
