import 'medicine.dart';
import 'store.dart';

class SampleData {
  static const stores = <Store>[
    Store(
      id: 1,
      name: 'Downtown Branch',
      chain: 'Mercury Drug',
      address: 'Daang Maharlika Highway, Brgy Gredu',
      phone: '(555) 010-1001',
      distanceKm: 0.7,
      isOpen: true,
    ),
    Store(
      id: 2,
      name: 'Westside Branch',
      chain: 'Mercury Drug',
      address: '45 Elm Ave, Westside',
      phone: '(555) 010-1002',
      distanceKm: 2.2,
      isOpen: false,
    ),
    Store(
      id: 3,
      name: 'City Center Branch',
      chain: 'Rose Pharmacy',
      address: 'Panabo Highway, Maharlika Street',
      phone: '(555) 010-2001',
      distanceKm: 1.5,
      isOpen: true,
    ),
    Store(
      id: 4,
      name: 'Gaisano Branch',
      chain: 'Rose Pharmacy',
      address: 'Gaisano Grand Mall, Quezon Street',
      phone: '(555) 010-2002',
      distanceKm: 3.0,
      isOpen: true,
    ),
    Store(
      id: 5,
      name: 'Downtown Branch',
      chain: 'Generika Drugstore',
      address: 'Quezon Street, Panabo Warf',
      phone: '(555) 010-3001',
      distanceKm: 2.8,
      isOpen: true,
    ),
    Store(
      id: 6,
      name: 'Uptown Branch',
      chain: 'Generika Drugstore',
      address: '201 Pine Ave, Uptown',
      phone: '(555) 010-3002',
      distanceKm: 4.6,
      isOpen: false,
    ),
    Store(
      id: 7,
      name: 'Central Branch',
      chain: 'The Generics Pharmacy',
      address: 'Qurino Street, NightMarket',
      phone: '(555) 010-4001',
      distanceKm: 1.9,
      isOpen: true,
    ),
    Store(
      id: 8,
      name: 'Highway Branch',
      chain: 'The Generics Pharmacy',
      address: 'Panabo Warf Road, Bpi Direct',
      phone: '(555) 010-4002',
      distanceKm: 5.2,
      isOpen: true,
    ),
  ];

  static const medicines = <Medicine>[
    Medicine(
      id: 1,
      name: 'Paracetamol',
      dosage: '500mg Tablet',
      genericName: 'Acetaminophen',
      description:
          'Analgesic and antipyretic used to relieve fever and mild pain.',
      price: 1.50,
      stock: 120,
      storeId: 1,
    ),
    Medicine(
      id: 2,
      name: 'Ibuprofen',
      dosage: '200mg Tablet',
      genericName: 'Ibuprofen',
      description:
          'NSAID for pain relief and inflammation reduction. Take with food.',
      price: 2.00,
      stock: 0,
      storeId: 1,
    ),
    Medicine(
      id: 3,
      name: 'Amoxicillin',
      dosage: '500mg Capsule',
      genericName: 'Amoxicillin',
      description:
          'Broad-spectrum penicillin antibiotic for bacterial infections. Use as prescribed.',
      price: 8.99,
      stock: 25,
      storeId: 2,
    ),
    Medicine(
      id: 4,
      name: 'Aspirin',
      dosage: '325mg Tablet',
      genericName: 'Acetylsalicylic Acid',
      description:
          'NSAID used for pain, fever, and as antiplatelet at low doses.',
      price: 1.75,
      stock: 85,
      storeId: 1,
    ),
    Medicine(
      id: 5,
      name: 'Diphenhydramine',
      dosage: '25mg Tablet',
      genericName: 'Diphenhydramine HCl',
      description:
          'Antihistamine for allergies and short-term insomnia; may cause drowsiness.',
      price: 2.50,
      stock: 45,
      storeId: 2,
    ),
    Medicine(
      id: 6,
      name: 'Cetirizine',
      dosage: '10mg Tablet',
      genericName: 'Cetirizine',
      description:
          'Second-generation antihistamine for allergic rhinitis and urticaria.',
      price: 1.20,
      stock: 60,
      storeId: 3,
    ),
    Medicine(
      id: 7,
      name: 'Loperamide',
      dosage: '2mg Capsule',
      genericName: 'Loperamide',
      description:
          'Antidiarrheal to reduce stool frequency; do not use with high fever.',
      price: 1.75,
      stock: 0,
      storeId: 4,
    ),
    Medicine(
      id: 8,
      name: 'Loratadine',
      dosage: '10mg Tablet',
      genericName: 'Loratadine',
      description: 'Non-drowsy antihistamine for allergy symptom relief.',
      price: 1.80,
      stock: 90,
      storeId: 3,
    ),
    Medicine(
      id: 9,
      name: 'Ranitidine',
      dosage: '150mg Tablet',
      genericName: 'Ranitidine',
      description:
          'H2 blocker for acid reduction; note many regions have regulatory advisories.',
      price: 2.99,
      stock: 35,
      storeId: 4,
    ),
    Medicine(
      id: 10,
      name: 'Metronidazole',
      dosage: '250mg Tablet',
      genericName: 'Metronidazole',
      description:
          'Antibiotic/antiprotozoal for anaerobic infections; avoid alcohol during therapy.',
      price: 3.25,
      stock: 55,
      storeId: 3,
    ),
    Medicine(
      id: 11,
      name: 'Omeprazole',
      dosage: '20mg Capsule',
      genericName: 'Omeprazole',
      description: 'Proton pump inhibitor for GERD and acid-related disorders.',
      price: 5.99,
      stock: 50,
      storeId: 5,
    ),
    Medicine(
      id: 12,
      name: 'Salbutamol',
      dosage: '2mg/5mL Syrup',
      genericName: 'Albuterol (Salbutamol)',
      description: 'Short-acting bronchodilator for relief of bronchospasm.',
      price: 3.50,
      stock: 10,
      storeId: 6,
    ),
    Medicine(
      id: 13,
      name: 'Fluoxetine',
      dosage: '20mg Capsule',
      genericName: 'Fluoxetine',
      description:
          'SSRI antidepressant; do not stop abruptly; monitor mood changes.',
      price: 7.50,
      stock: 40,
      storeId: 5,
    ),
    Medicine(
      id: 14,
      name: 'Atorvastatin',
      dosage: '20mg Tablet',
      genericName: 'Atorvastatin',
      description:
          'Statin for lowering cholesterol; best taken in the evening.',
      price: 6.75,
      stock: 65,
      storeId: 6,
    ),
    Medicine(
      id: 15,
      name: 'Cough Syrup',
      dosage: '10mg/5mL',
      genericName: 'Dextromethorphan (example)',
      description:
          'Cough suppressant; use as directed; not for productive coughs unless advised.',
      price: 2.25,
      stock: 0,
      storeId: 5,
    ),
    Medicine(
      id: 16,
      name: 'Metformin',
      dosage: '500mg Tablet',
      genericName: 'Metformin',
      description: 'First-line therapy for type 2 diabetes; take with meals.',
      price: 4.25,
      stock: 70,
      storeId: 7,
    ),
    Medicine(
      id: 17,
      name: 'Losartan',
      dosage: '50mg Tablet',
      genericName: 'Losartan',
      description:
          'ARB for hypertension; monitor blood pressure and kidney function.',
      price: 6.10,
      stock: 0,
      storeId: 8,
    ),
    Medicine(
      id: 18,
      name: 'Lisinopril',
      dosage: '10mg Tablet',
      genericName: 'Lisinopril',
      description:
          'ACE inhibitor for hypertension/heart failure; may cause cough.',
      price: 5.50,
      stock: 48,
      storeId: 7,
    ),
    Medicine(
      id: 19,
      name: 'Amlodipine',
      dosage: '5mg Tablet',
      genericName: 'Amlodipine',
      description: 'Calcium channel blocker for hypertension and angina.',
      price: 4.99,
      stock: 72,
      storeId: 8,
    ),
    Medicine(
      id: 20,
      name: 'Vitamin C',
      dosage: '500mg Tablet',
      genericName: 'Ascorbic Acid',
      description:
          'Vitamin supplement for immune support and antioxidant effects.',
      price: 1.50,
      stock: 150,
      storeId: 7,
    ),
    Medicine(
      id: 21,
      name: 'Multivitamin',
      dosage: 'Daily Formula',
      genericName: 'Various (multivitamin)',
      description: 'Broad-spectrum vitamin/mineral supplement; once daily use.',
      price: 3.99,
      stock: 95,
      storeId: 8,
    ),
    Medicine(
      id: 22,
      name: 'Iron Supplement',
      dosage: '65mg Tablet',
      genericName: 'Ferrous Sulfate',
      description:
          'Iron supplement for deficiency; may cause GI upset; take with vitamin C.',
      price: 2.75,
      stock: 58,
      storeId: 7,
    ),
    // Replicated common medicines across multiple branches
    Medicine(
      id: 23,
      name: 'Paracetamol',
      dosage: '500mg Tablet',
      genericName: 'Acetaminophen',
      description:
          'Analgesic and antipyretic used to relieve fever and mild pain.',
      price: 1.45,
      stock: 110,
      storeId: 2,
    ),
    Medicine(
      id: 24,
      name: 'Paracetamol',
      dosage: '500mg Tablet',
      genericName: 'Acetaminophen',
      description:
          'Analgesic and antipyretic used to relieve fever and mild pain.',
      price: 1.60,
      stock: 95,
      storeId: 3,
    ),
    Medicine(
      id: 25,
      name: 'Ibuprofen',
      dosage: '200mg Tablet',
      genericName: 'Ibuprofen',
      description:
          'NSAID for pain relief and inflammation reduction. Take with food.',
      price: 2.10,
      stock: 80,
      storeId: 2,
    ),
    Medicine(
      id: 26,
      name: 'Cetirizine',
      dosage: '10mg Tablet',
      genericName: 'Cetirizine',
      description:
          'Second-generation antihistamine for allergic rhinitis and urticaria.',
      price: 1.25,
      stock: 75,
      storeId: 4,
    ),
    Medicine(
      id: 27,
      name: 'Omeprazole',
      dosage: '20mg Capsule',
      genericName: 'Omeprazole',
      description: 'Proton pump inhibitor for GERD and acid-related disorders.',
      price: 6.10,
      stock: 45,
      storeId: 6,
    ),
    Medicine(
      id: 28,
      name: 'Vitamin C',
      dosage: '500mg Tablet',
      genericName: 'Ascorbic Acid',
      description:
          'Vitamin supplement for immune support and antioxidant effects.',
      price: 1.55,
      stock: 130,
      storeId: 8,
    ),
  ];
}
